### ISSUE TITLE
Capitalization error in commit #dfe8040

### ISSUE THREAD

**Issue by ryleysevier** [JustinRackley/Assignment-1-UM#1]
I noticed a capitalization error on this commit with the H and the W on
dfe8040

**Comment by JustinRackley** [comment]
Thanks for keeping me on my toes, Ryley!  However this is not an issue, as the assignment was to print "hello world" in lower case! thank you!

**Comment by ryleysevier** [comment]
Thanks, closing and wasn't an issue.
